### ISSUE TITLE
issues with notebook code

### ISSUE THREAD

**Issue by yfoo** [mzaradzki/neuralnets#5]
Hi, I'm trying to follow along the post below utilizing keras, with tensorflow backend.

https://aboveintelligent.com/face-recognition-with-keras-and-opencv-2baf2a83b799

Combined with the notebook you list:

https://github.com/mzaradzki/neuralnets/blob/master/vgg_faces_keras/vgg_faces_demo.ipynb

The first problem is in this part of the code:

if False:
    data = loadmat('vgg-face.mat', matlab_compatible=False, struct_as_record=False)
    l = data['layers']
    description = data['meta'][0,0].classes[0,0].description
else:
    data = loadmat('vgg_face_matconvnet/data/vgg_face.mat', matlab_compatible=False, struct_as_record=False)
    net = data['net'][0,0]
    l = net.layers
    description = net.classes[0,0].description

The code hits the else block and fails to get past:

 net = data['net'][0,0]

Traceback (most recent call last):
  File "keras-vg-demo.py", line 95, in <module>
    net = data['net'][0,0]
KeyError: 'net'

Due to the net key not existing. Maybe it doesn't exist in the matlab file vgg-face.mat? I've tried to use the method in the false section instead focusing on "layers" instead of net, I get passed that error, but then I get to:

Traceback (most recent call last):
  File "keras-vg-demo.py", line 144, in <module>
    copy_mat_to_keras(facemodel)
  File "keras-vg-demo.py", line 137, in copy_mat_to_keras
    assert (f_l_weights.shape == kmodel.layers[kindex].get_weights()[0].shape)
AssertionError

Help!
I'm trying to get some code in keras working to do basic facial recognition, and secondly face detection.

Thank you for your help!  :)

**Comment by mzaradzki** [comment]
Hi

The hard-coded "if False" in the notebook has to be set to True or False depending in the .mat file you downloaded from the previous text cell in the notebook:

Download from console with :
wget http://www.vlfeat.org/matconvnet/models/vgg-face.mat
Alternatively :
wget http://www.robots.ox.ac.uk/~vgg/software/vgg_face/src/vgg_face_matconvnet.tar.gz

I believe as it is (if False) it assumes you downloaded the second link: depending on the link the file is not structured the same way

If this comment does not help (let me know) I will download again the .mat file to clarify this point further

**Comment by yfoo** [comment]
Hi,

Ya, so fooling with settting the first block to False, you get:

Traceback (most recent call last):

  File "keras-vg-demo.py", line 93, in <module>

    net = data['net'][0,0]

KeyError: 'net


And setting to true you get:

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library
wasn't compiled to use FMA instructions, but these are available on your
machine and could speed up CPU computations.

Traceback (most recent call last):

  File "keras-vg-demo.py", line 143, in <module>

    copy_mat_to_keras(facemodel)

  File "keras-vg-demo.py", line 136, in copy_mat_to_keras

    assert (f_l_weights.shape ==
kmodel.layers[kindex].get_weights()[0].shape)

AssertionError


The file name is:

vgg-face.mat
Thanks!

I can send you the code I'm running if that would help, but it's pretty
much 100% taken from the notebook.

**Comment by mzaradzki** [comment]
Hi,

The new bug you have is probably related to the settings in the keras.json file that is documented here;
https://keras.io/backend/

One variable that impacts the convolution tensor shapes is: "image_data_format"
What value does it have in your configuration ?

When I wrote this notebook I think I used "th" (legacy values) for it as I also used Theano. Anyway it is easy to translate from one value to another one as this is just about permuting the dimension orders.

This is a point I needs to clarify in the documentation cells of the notebook to facilitates replication !

In the Keras help link above you will find function "set_image_dim_ordering" that should tweak it without changing the Json file.

If you dont manage to fix it with this function I will run it with your settings to see.

**Comment by yfoo** [comment]
Ok I'll take a look at that setting and report back thanks!

**Comment by yfoo** [comment]
Hi, this is what I have:

{

    "epsilon": 1e-07,

    "floatx": "float32",

    "image_data_format": "channels_last",

    "backend": "tensorflow"

**Comment by mzaradzki** [comment]
Ok, great, we are on the right track!

It needs something like the following (A) or (B) at the beginning of the notebook:

A)
>>> from keras import backend as K
>>> K.set_image_data_format( 'channels_first' )

B) 
>>> from keras import backend as K
>>> K.set_image_dim_ordering( 'th' )

Reading the doc I think the 2 things are equivalent but that (A) is the most recent version

**Comment by yfoo** [comment]
Hi,

Both of those settings cause the following early on:

tensorflow/python/framework/common_shapes.py", line 676, in
_call_cpp_shape_fn_impl

    raise ValueError(err.message)

ValueError: Negative dimension size caused by subtracting 2 from 1 for
'max_pooling2d_2/MaxPool' (op: 'MaxPool') with input shapes: [?,112,1,128].

Where as the program gets farther without those with the original error:

Traceback (most recent call last):

  File "keras-vg-demo.py", line 146, in <module>

    copy_mat_to_keras(facemodel)

  File "keras-vg-demo.py", line 139, in copy_mat_to_keras

    assert (f_l_weights.shape ==
kmodel.layers[kindex].get_weights()[0].shape)

AssertionError

**Comment by mzaradzki** [comment]
I just debugged it running *Keras 2*, *TensorFlow* and *"image_data_format":"channels_last"*

Code has been pushed on Git repo.

The last bug you had came from the fact the Input tensor was potentially not ordered the right way depending on the "image_data_format" value at this line:
mdl.add( Permute((1,2,3), input_shape=(224,224,3)) ) # WARNING : 0 is the sample dim

Similarly in "copy_mat_to_keras" function there was a potential axis ordering issue.
As well as in "pred" function.

So I added the necessary information and code changes.

I used your default value for *"image_data_format":"channels_last"* as it seems to be more common.

Also if you use Keras 1 in "convblock" and "vgg_face_blank" functions I left as comments the Conv2D syntax.

**Comment by yfoo** [comment]
Thank you for the update! I'll check it out!

**Comment by yfoo** [comment]
Thanks, it works great now! Now to get in and get dirty, and figure this
stuff out more deeply :)

Can you point me in the direction of how to go about training a network
with a new input? For instance, say the vggface network didn't have george
clooney included, and you'd like to be able to classify an image of george
clooney correctly.

Have a good one!
Chris
