### ISSUE TITLE
the reason of using pascal-fcn16s-dag.mat instead of weight provided by Keras pretrained model

### ISSUE THREAD

**Issue by huaiyanggongzi** [mzaradzki/neuralnets#6]
Hi mzaradzki,

I have a question regarding your implementation of `fcn16s_segmentation.ipynb`, which introduces the weight of `pascal-fcn16s-dag.mat` for pre-trained model. Currently, [Keras](https://github.com/fchollet/deep-learning-models/releases) already provides pre-trained weight. 
In order to leverage the mat-based weight, we have to use the function of `copy_mat_to_keras`,which can add one more layer of complexity. Are there any specific reason for this? Thanks a lot.

Huaiyang

**Comment by mzaradzki** [comment]
Hi !

Apologies for the very late reply

I thought it was great to have the possibility to experiment with different weights so as to compare the impact of the training method and to have better control on it.
For example in the notebook I compare 3 different weight sets.
